### ISSUE TITLE
Add license to setup.py and LICENSE file

### ISSUE THREAD

**Issue by grantjenks** [reactive-python/reactpy-jupyter#17]
I'm interested in experimenting with this at work but our build process requires that we check the license of all code that is imported. I noticed that `idom` is licensed as "MIT" in setup.py and includes a LICENSE file. Would you be willing to do that for `idom-jupyter` as well?

**Comment by rmorshea** [comment]
Added the license file. Will make a release containing it shortly.

**Comment by rmorshea** [comment]
@grantjenks version `0.6.2` should now contain an MIT license file in the distribution

**Comment by grantjenks** [comment]
Thanks!
