### ISSUE TITLE
Widgets not displaying

### ISSUE THREAD

**Issue by WulkanHefajstos** [reactive-python/reactpy-jupyter#19]
Hey,

After recent release of `idom==0.36.3` i updated my environment and all components stopped working in JupyterLab (even simple example from readme file).
They're simply not displaying and in the browser console, following error is logged:

![obraz](https://user-images.githubusercontent.com/32578233/154816181-c4e539f3-ea6b-4c04-9bbd-80396fa1f76c.png)

After downgrading `idom` to version `0.36.2`, everything started working fine.

I've just started playing with idom (i love it!) so i'm afraid i'm not able to help you guys figure out what's wrong.

Cheers!

**Comment by rmorshea** [comment]
0.36.3 turned out to be a breaking change. There will be an update to `idom-jupyter` that should fix the issue.

**Comment by rmorshea** [comment]
@WulkanHefajstos if you're at all interested in contributing to the project I'd be happy to answer questions about how to do so during [office hours](https://github.com/idom-team/idom/discussions/312)

**Comment by rmorshea** [comment]
I just released `idom-jupyter` 0.7.4 which should fix this. Please re-open this if that doesn't resolve the problem.
