### ISSUE TITLE
Model class 'IdomModel' from module 'idom-client-jupyter' is loaded but can not be instantiated

### ISSUE THREAD

**Issue by rafaellichen** [reactive-python/reactpy-jupyter#24]
Launching binder notebook using the link from README results in the following error after executing cells.

```js
[Open Browser Console for more detailed log - Double click to close this message]
Model class 'IdomModel' from module 'idom-client-jupyter' is loaded but can not be instantiated
TypeError: o._deserialize_state is not a function
    at u._make_model (https://hub.ovh2.mybinder.org/user/idom-team-idom-jupyter-lw0tbzbx/nbextensions/jupyter-js-widgets/extension.js?v=20221223025821:2:747339)
```

build logs:
```
Found built image, launching...
Launching server...
Server requested
2022-12-23T03:40:51.256234Z [Normal] Successfully assigned ovh2/jupyter-idom-2dteam-2didom-2djupyter-2d15jeanpl to user-202211a-node-c616e7
2022-12-23T03:40:52Z [Normal] Container image "jupyterhub/mybinder.org-tc-init:2020.12.4-0.dev.git.4289.h140cef5" already present on machine
2022-12-23T03:40:52Z [Normal] Created container tc-init
2022-12-23T03:40:52Z [Normal] Started container tc-init
2022-12-23T03:40:53Z [Normal] Pulling image "2lmrrh8f.gra7.container-registry.ovh.net/mybinder-builds/r2d-g5b5b759idom-2dteam-2didom-2djupyter-67cfe6:276e3ada3bcbff2f8254c2fa339ee3aeaf9b2b1e"
2022-12-23T03:41:46Z [Normal] Successfully pulled image "2lmrrh8f.gra7.container-registry.ovh.net/mybinder-builds/r2d-g5b5b759idom-2dteam-2didom-2djupyter-67cfe6:276e3ada3bcbff2f8254c2fa339ee3aeaf9b2b1e" in 53.041814721s
2022-12-23T03:41:46Z [Normal] Created container notebook
2022-12-23T03:41:47Z [Normal] Started container notebook
```

**Comment by rmorshea** [comment]
Thanks for reporting this. There's been a lot of changes recently to idom and not all of them have made their way into idom-jupyter just yet. I suspect that's probably the cause.

**Comment by rafaellichen** [comment]
> Thanks for reporting this. There's been a lot of changes recently to idom and not all of them have made their way into idom-jupyter just yet. I suspect that's probably the cause.

@rmorshea thanks for the quick response. very strange behavior here.
launching through `https://binder.mybinder.ovh/`, resulting in `https://hub-binder.mybinder.ovh/user/idom-team-idom-jupyter-exdbosus/lab`, and the examples work.
launching through `https://mybinder.org/`, resulting in `https://hub.ovh2.mybinder.org/user/idom-team-idom-jupyter-v38662cg/lab`, and the examples don't work

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/15823067/209291244-8435d56c-ad03-410f-a1bb-37a214bf453d.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/15823067/209291332-7bab2846-b96e-485f-88c8-7b5b83aef621.png">

**Comment by rmorshea** [comment]
That's very helpful information. Would have been very hard to find that out on my own.

If you open the debug console on your browser, do you get any interesting tracebacks?

**Comment by rmorshea** [comment]
If you open the debug console on your browser, do you get any interesting tracebacks?

**Comment by rafaellichen** [comment]
> If you open the debug console on your browser, do you get any interesting tracebacks?

no

**Comment by rmorshea** [comment]
Maybe related: https://github.com/jupyterhub/mybinder.org-deploy/issues/2407

**Comment by rmorshea** [comment]
For some reason when I launch through https://mybinder.org I end up with instances deployed at https://hub-binder.mybinder.ovh. However, when I deploy via https://ovh2.mybinder.org/ I get redirected to https://hub.ovh2.mybinder.org which, as you explain, results in errors.

**Comment by rmorshea** [comment]
I have a [draft PR](https://github.com/idom-team/idom-jupyter/pulls) to upgrade to the latest [widget template](https://github.com/jupyter-widgets/widget-cookiecutter) and I see similar errors when I deploy that branch, even via https://mybinder.org. Hard to say exactly what's going on at the moment. Will keep digging when I find time though.

**Comment by rafaellichen** [comment]
> For some reason when I launch through https://mybinder.org I end up with instances deployed at https://hub-binder.mybinder.ovh. However, when I deploy via https://ovh2.mybinder.org/ I get redirected to https://hub.ovh2.mybinder.org which, as you explain, results in errors.

even when i use the same link `https://binder.mybinder.ovh/` on this repository and my [forked version](https://github.com/rafaellichen/idom-jupyter) (without changes), this repository works while my forked version results in same error. :expressionless:

**Comment by rmorshea** [comment]
I'm unable to reproduce in ovh2 now. I'm also unable to reproduce when testing this out with [repo2docker](https://repo2docker.readthedocs.io/en/latest/). I'm not really sure what to do here at the moment given that I'm no longer able to reproduce. Will close for now, but please comment if this persists.

**Comment by rafaellichen** [comment]
@rmorshea can you verify this for me? thanks.
it doesn't work for me even though the code is the same. originally thought it could be js cache issue, but same problem persists under incognito mode.
https://mybinder.org/v2/gh/rafaellichen/idom-jupyter/276e3ada3bcbff2f8254c2fa339ee3aeaf9b2b1e?urlpath=lab%2Ftree%2Fnotebooks%2Fintroduction.ipynb

**Comment by rmorshea** [comment]
Ok, I just double checked and I think I was looking at my open PR when testing things out. I can confirm that `main` is broken. However, my changes in https://github.com/idom-team/idom-jupyter/pull/25 seem to fix things.

**Comment by rmorshea** [comment]
I'll merge that PR and cut a release shortly.

**Comment by rmorshea** [comment]
Ok, the PR has been merged. It would be great to get confirmation that everything works on your end before I do a release.

**Comment by rafaellichen** [comment]
> Ok, the PR has been merged. It would be great to get confirmation that everything works on your end before I do a release.

yes, can confirm it works even for my forked version of this repo now. thanks.

**Comment by rmorshea** [comment]
`idom-jupyter` version 0.7.7 has been released! Let me know if you encounter any more issues.
